<?php

// *******************************************************************************************
//     BLOCKS
// *******************************************************************************************

/**
 * Implements hook_block_info_alter().
 */
function rd_multilanguage_block_info_alter(&$blocks, $theme, $code_blocks) {
  // enable language selector block in the header
  if (isset($blocks['locale']['language'])) {
      $blocks['locale']['language']['status'] = 1;
      $blocks['locale']['language']['region'] = 'header';
  }
}



// *******************************************************************************************
//     TRANSLATIONS
// *******************************************************************************************

// From https://fosswiki.liip.ch/display/DRUPAL/Script+creation+of+languages+and+import+po+files

/**
 * Add translations from a PO file.
 * This will populate the locales_target table in the database
 * with the strings from the PO file.
 *
 * @param $langcode string (e.g. fr, de, it)
 * @param $poFile string full path to .po file
 * @param $mode const LOCALE_IMPORT_OVERWRITE (overwrite existing translations) or LOCALE_IMPORT_KEEP (only import new strings)
 * @param $group string Text group to import PO file into (eg. 'default' for interface translations)
 * @return bool success
 */
function rd_multilanguage_update_load_language($langcode, $poFile, $mode=LOCALE_IMPORT_OVERWRITE, $group='default') {
  // mimic a drupal uploaded file object, with the necessary info needed by _locale_import_po
  $file = new stdClass;
  $file->uri = $poFile;
  $file->filename = basename($poFile);
  return _locale_import_po($file, $langcode, $mode, $group);
}

/**
 * Find all po files under a given path
 *
 * @param $path string
 * @param $recurse boolean
 * @return array of string paths to po files
 */
function rd_multilanguage_find_po_files($path, $recurse=TRUE) {
  $path = rtrim($path, '/') . '/*';
  $pattern = '/\.po$/';
  $files = array();
  foreach (glob ($path) as $fullname) {
    if ($recurse && is_dir($fullname)) {
      $files = array_merge($files, rd_multilanguage_find_po_files($fullname, $recurse));
    } else if (preg_match($pattern, $fullname)) {
      $files[] = $fullname;
    }
  }
  return $files;
}


function rd_mulilanguage_update_all_custom_translations(){
  $path = 'profiles/rdigital/modules/custom';
  $files = rd_multilanguage_find_po_files($path, TRUE);

  // Organize all files by language and text_group
  // NOTE: expected name lang_code.text_group.po (i.e: es.fields.po)
  foreach ($files as $fullname) {
    $basename = basename($fullname);
    $file_name_array = explode('.', $basename);
    $lang_code = $file_name_array[0];
    $text_group = $file_name_array[1];
    $po_files[$lang_code][$text_group] = $fullname;
  }

  //update all translations by language
  foreach ($po_files as $language_code => $lang_text_formats) {
    foreach ($lang_text_formats as $text_format => $po_fullname) {
      rd_multilanguage_update_load_language($language_code, $po_fullname, LOCALE_IMPORT_OVERWRITE, $text_format);
    }
  }
}

/**
 * Implements hook_menu().
 */
function rd_multilanguage_menu() {
  $t = get_t();
  $items['admin/config/regional/translate/rd_update'] = array(
    'title' => $t('Recat Digital Update'),
    'description' => $t('Update Recat Digital translations'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rd_multilanguage_update_translations_form'),
    'access arguments' => array('translate interface'),
    'weight' => 21,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function rd_multilanguage_update_translations_form($form, &$form_state) {
  $t = get_t();
  $form['form_title'] = array(
    '#markup' => '<h1>' . $t('Update all Recat Digital translations') . '</h1>' . $t('NOTE: All languages and format texts will be translated') . '<p><p>',
  );
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => $t('Update translations'),
  );
  return $form;
}

function rd_multilanguage_update_translations_form_submit($form, &$form_state) {
  rd_mulilanguage_update_all_custom_translations();
}


// *******************************************************************************************
//     INVESTIGATION
//     Functions not used but left here just in case they're needed in the future
// *******************************************************************************************


// KO
function _update_string_translation() {
  //https://gist.github.com/opi/5335785
  $report = array(
    'skips'=>0,
    'updates'=>0,
    'deletes'=>0,
    'additions'=>0
  ); // ??
  $source = "Spain";
  $translation = "EspaNa";
  $textgroup = 'taxonomy'; // field , node, default, menu ...
  $langcode = 'es'; // 'en', 'de'
  $mode = LOCALE_IMPORT_KEEP; // LOCALE_IMPORT_KEEP
  $location = 'taxonomy:term:3:name'; //  'menu:menu:management:title', '/node/3', ...
  $context = 'term:3:name';

  _locale_import_one_string_db($report, $langcode, $context, $source, $translation, $textgroup, $location, $mode);

  // Clear locale cache.
  cache_clear_all('locale:', 'cache', TRUE);


}

//OK
function _yourmodule_profile_create_term_translation() {
  //http://blog.studio.gd/blog/id/17/drupal__how_to_create_and_translate_a_taxonomy_term_programmatically
    $context = array(
    'rd_f_appo_treatment_measures',
    'rd_ct_appointment',
    'label',
  );
  $textgroup = 'field';
  i18n_string_textgroup($textgroup)->update_translation($context, 'es', 'MEDIDAS TRATAMIENTO');

  //others:
  //variable_set('language_content_type_<bundle_name>',TRANSLATION_ENABLED);
  //variable_del('language_content_type_<bundle_name>');
  //locale_language_providers_weight_language
  //language_negotiation_language
}

// Interesting links
// http://blog.studio.gd/blog/id/17/drupal__how_to_create_and_translate_a_taxonomy_term_programmatically

