<?php

// *******************************************************************************************
//     VIEWS
// *******************************************************************************************

/**
* Implementation of hook_views_api().
*/
function rd_treatment_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'rd_treatment')
  );
}



// *******************************************************************************************
//     PANELS
// *******************************************************************************************

/**
* Implementation of hook_ctools_plugin_api().
*/
function rd_treatment_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function rd_treatment_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
    return "plugins/". $plugin;
  }
  if ($module == 'page_manager' && $plugin == 'content_types' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}


// *******************************************************************************************
//     JAVASCRIPT
// *******************************************************************************************




function rd_treatment_js_alter(&$javascript) {
  if (isset($javascript['misc/autocomplete.js'])){
    $file = drupal_get_path('module', 'rd_treatment') . '/js/autocomplete.js';
    $javascript['misc/autocomplete.js']['data'] = $file;
  }
}


// *******************************************************************************************
//     MENU
// *******************************************************************************************

/**
 * Implements hook_menu().
 */
function rd_treatment_menu(){
  $items = array();

  $items['patient/%/create-treatment'] = array(
    'page callback' => 'rd_treatment_create_treatment_callback',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;

}

function rd_treatment_create_treatment_callback($patient_nid){
  $patient = node_load($patient_nid);
  global $user;
  $user = user_load($user->uid);
  //Create Treatment
  $treatment = new stdClass();
  $treatment->type = 'rd_ct_treatment';
  $treatment->uid = $user->uid;
  $treatment->language = LANGUAGE_NONE; // TO DO: review
  $treatment->status = 1;
  $treatment->promote = 0;
  $treatment->sticky = 0;
  $treatment->title = $patient->title;
  $treatment->rd_f_treat_related_patient['und'][0]['target_id'] = $patient->nid;
  $treatment->rd_f_treat_related_pract['und'][0]['target_id'] = $user->uid;
  $treatment->rd_f_treat_date_time['und'][0]['value'] = date('Y-m-d H:i:s'); //IMP: store UTC time, not the timezone time
  if (isset($user->rd_f_access_user_centre['und'][0]['tid'])) {
    $treatment->rd_f_access_treat_centre['und'][0]['tid'] = $user->rd_f_access_user_centre['und'][0]['tid'];
  }
  node_save($treatment);
  drupal_goto('treatment/' . $patient_nid . '/' . $treatment->nid);
}
