<?php


// *******************************************************************************************
//     NODE ACTIONS
// *******************************************************************************************

// TO DO



// *******************************************************************************************
//     VIEWS
// *******************************************************************************************



/**
* Implementation of hook_views_api().
*/
// function rd_appointment_views_api() {
//   return array(
//     'api' => '3.0',
//     'path' => drupal_get_path('module', 'rd_patient')
//   );
// }




// *******************************************************************************************
//     JAVASCRIPT
// *******************************************************************************************




function rd_treatment_js_alter(&$javascript) {
  if (isset($javascript['misc/autocomplete.js'])){
    $file = drupal_get_path('module', 'rd_treatment') . '/js/autocomplete.js';
    $javascript['misc/autocomplete.js']['data'] = $file;
  }
}
