<?php

// *******************************************************************************************
//     VIEWS
// *******************************************************************************************

/**
* Implementation of hook_views_api().
*/
function rd_treatment_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'rd_treatment')
  );
}



// *******************************************************************************************
//     PANELS
// *******************************************************************************************

/**
* Implementation of hook_ctools_plugin_api().
*/
function rd_treatment_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function rd_treatment_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
    return "plugins/". $plugin;
  }
  if ($module == 'page_manager' && $plugin == 'content_types' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}


// *******************************************************************************************
//     JAVASCRIPT
// *******************************************************************************************




function rd_treatment_js_alter(&$javascript) {
  if (isset($javascript['misc/autocomplete.js'])){
    $file = drupal_get_path('module', 'rd_treatment') . '/js/autocomplete.js';
    $javascript['misc/autocomplete.js']['data'] = $file;
  }
}


