<?php

// *******************************************************************************************
//     PERMISSIONS
// *******************************************************************************************

/**
 * Implements hook_permission().
 */
function rd_secretariat_permission() {
  return array(
    t('access secretariat actions') => array(
      'title' => t('access secretariat actions'),
      'description' => t('Allow access to the secretariat actions'),
    ),
  );
}

// *******************************************************************************************
//     MENU
// *******************************************************************************************

/**
 * Implements hook_menu().
 */
function rd_secretariat_menu() {
  // Secretariat
  $items['secretariat'] = array(
    'title' => t('Secretariat'),
    'page callback' => 'rd_sec_menu_options',
    'access arguments' => array('access secretariat actions'),
    'menu_name' => 'main-menu',
    'expanded' => TRUE,
    'weight' => 2,
    'type' => MENU_NORMAL_ITEM,
  );

  // 1 - Patients
  $items['secretariat/patients'] = array(
    'title' => t('Patients'),
    'description' => t('Import or Create Patients'),
    'access arguments' => array('access secretariat actions'),
    //'menu_name' => 'main-menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rd_sec_import_patients_form'),
    'access arguments' => array('access secretariat actions'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );
  $items['secretariat/patients/import'] = array(
    'title' => t('Import'),
    'description' => t('Import or update Patients using an Excel file'),
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['secretariat/patients/create'] = array(
    'title' => t('Create'),
    'description' => t('Create a Patient'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rd_sec_create_patients_form'),
    'access arguments' => array('access secretariat actions'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  // NOTE: This code is not needed as you can use View config (Page Settings) to set this up:
  //        - Path: 'secretariat/patients/manage'
  //        - Menu:
  //           - Type: Menu tab
  //           - Menu: Main Menu
  // $items['secretariat/patients/manage'] = array(
  //   'title' => t('Manage'),
  //   'description' => t('Edit or delete a Patient'),
  //   'page callback' => 'views_embed_view',
  //   'page arguments' => array('patients_secretary'),
  //   'access arguments' => array('access secretariat actions'),
  //   //'file path' => drupal_get_path('module', 'views'),
  //   //'file' => 'views.module',
  //   'weight' => 3,
  //   'type' => MENU_LOCAL_TASK,
  // );

  // 2 - Practitioners
  // Manage by Views

  // 3 - Access Keys
  $items['secretariat/access_keys'] = array(
    'title' => t('Access Keys'),
    'description' => t('Create Access Keys'),
    'access arguments' => array('access secretariat actions'),
    //'menu_name' => 'main-menu',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rd_sec_create_access_key_form'),
    'access arguments' => array('access secretariat actions'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 3,
  );
  $items['secretariat/access_keys/create'] = array(
    'title' => t('Create'),
    'description' => t('Create Access Keys'),
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['secretariat/access_keys/link'] = array(
    'title' => t('Link'),
    'description' => t('Link Access Key with Patients and Practitioners'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rd_sec_link_access_key_form'),
    'access arguments' => array('access secretariat actions'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $items['secretariat/access_keys/delete'] = array(
    'title' => t('Delete'),
    'description' => t('Delete Access Key for Patients and Practitioners'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rd_sec_delete_access_key_form'),
    'access arguments' => array('access secretariat actions'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

// SECRETARIAT

/**
* Page callback for Secretariat
*/
function rd_sec_menu_options(){
  //dpm(menu_tree('main-menu'));
  $page_render = '';
  foreach (menu_tree('main-menu') as $key => $menu_primary_link) {
    if (isset($menu_primary_link['#href']) &&  $menu_primary_link['#href']== 'secretariat'){
      foreach ($menu_primary_link['#below'] as $key2 => $menu_secondary_link) {
        if (isset($menu_secondary_link['#title'])){
          $page_render .= '
            <div class="btn-group btn-group-lg" role="group">
                <a href="'. $menu_secondary_link['#href'] .'" class="btn btn-info" role="button">'
                . $menu_secondary_link['#title'] .
                '</a>
            </div>';
        }
      }
    }
  }
  return $page_render;
}

// PATIENTS

/**
* Page callback for Import Patients Form
*/
function rd_sec_import_patients_form($form, &$form_state) {

  $form['info'] = array(
    '#type' => 'markup',
    '#markup' => '<p>' . t('NOTE: Import or Update Patients') . '</p>',
  );

  $form['import'] = array(
    '#title' => t('CSV File'),
    '#type' => 'managed_file',
    '#description' => t('Choose the file and then click on Upload button. The uploaded csv will be imported and temporarily saved.'),
    '#upload_location' => 'public://secretaria/importar_pacientes/',
    '#upload_validators' => array(
      'file_validate_extensions' => array('csv'),
    ),
    '#required' => true,
  );

  $form['centre'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Centre'),
    '#options' => _get_vocabulary_terms('rd_voc_centre'),
    '#required' => true,
  );

  $access_keys = _get_vocabulary_terms('rd_voc_access_key');
  unset($access_keys[current(array_keys($access_keys))]); //remove the first element of the list: "0 - All"
  $form['access_keys'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Access Key'),
    '#options' => $access_keys,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import'),
  );

  return $form;
}

function rd_sec_import_patients_form_submit($form, &$form_state) {
  // Check to make sure that the file was uploaded to the server properly
  $uri = db_query("SELECT uri FROM {file_managed} WHERE fid = :fid", array(
    ':fid' => $form_state['input']['import']['fid'],
  ))->fetchField();
  if(!empty($uri)) {
    if(file_exists(drupal_realpath($uri))) {
      // Open the csv
      $handle = fopen(drupal_realpath($uri), "r");
      // Go through each row in the csv and run a function on it. In this case we are parsing by ',' (comma) characters.
      // If you want commas are any other character, replace the comma with it.
      while (($data = fgetcsv($handle, 0, ',', '"')) !== FALSE) {
        $operations[] = array(
          'rd_sec_import_batch_processing',  // The function to run on each row
          array($data, $form_state['values']['access_keys'], $form_state['values']['centre']),  // The row in the csv
        );
      }

      // Once everything is gathered and ready to be processed... well... process it!
      $batch = array(
        'title' => t('Importing CSV...'),
        'operations' => $operations,  // Runs all of the queued processes from the while loop above.
        'finished' => 'rd_sec_import_finished', // Function to run when the import is successful
        'error_message' => t('The installation has encountered an error.'),
        'progress_message' => t('Imported @current of @total products.'),
      );
      batch_set($batch);
      fclose($handle);
    }
  }
  else {
    drupal_set_message(t('There was an error uploading your file. Try it again or contact a System administator.'), 'error');
  }
}

/**
 * This function runs the batch processing and creates nodes with then given information
 */
function rd_sec_import_batch_processing($data, $access_key_list, $centre_list) {

  // required
  $patient_name = ucfirst($data[3]);
  $patient_first_surename = strtoupper($data[1]);
  $patient_number =  $data[0];
  // not required
  $patient_second_surename = strtoupper($data[2]);
  $patient_genre =  $data[4];
  $patient_dob =  $data[6];
  $patient_city =  $data[7];
  $patient_state =  $data[8];
  $patient_occupation =  $data[9];
  $patient_recommended =  $data[10];
  //$patient_notes =  $data[xxxxxx]; // field new and just for the site, not used on Excel
  $patient_homeopathy =  $data[14];
  $patient_c_medicine =  $data[12];
  $patient_a_therapies =  $data[13];
  $patient_a_type =  $data[5];
  $patient_t_before =  $data[15];
  $patient_o_symptoms =  $data[11];

  // Create or update Patient
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'rd_ct_patient')
    ->fieldCondition('rd_f_patient_excel_number', 'value', $patient_number, '=')
    ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');
  $result = $query->execute();

  // update
  if (!empty($result['node'])) {
    $key = array_keys($result['node']);
    $nid = reset($key);
    $node = node_load($nid);
  }
  // create
  else{
    global $user;
    $node = new stdClass();
    $node->type = 'rd_ct_patient';
    node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
    $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
    $node->uid = $user->uid;
  }

  $node->title = !empty($patient_second_surename) ? $patient_first_surename . ' ' . $patient_second_surename . ', ' . $patient_name : $patient_first_surename  . ', ' . $patient_name;
  $node->rd_f_patient_name['und'][0]['value'] = $patient_name;
  $node->rd_f_patient_first_surname['und'][0]['value'] = $patient_first_surename;
  $node->rd_f_patient_excel_number['und'][0]['value'] = $patient_number;
  if(!empty($patient_second_surename)) $node->rd_f_patient_second_surname['und'][0]['value'] = $patient_second_surename;
  if(!empty($patient_genre)) $node->rd_f_patient_genre['und'][0]['value'] = $patient_genre;
  if(!empty($patient_dob)){
    $dob_array = explode("/", $patient_dob);
    $node->rd_f_patient_dob['und'][0]['value'] = $dob_array[2] . '-' . $dob_array[1] . '-' . $dob_array[0] . ' 00:00:00';
  }
  if(!empty($patient_city)) $node->rd_f_patient_city['und'][0]['value'] = $patient_city;
  if(!empty($patient_state)) $node->rd_f_patient_state['und'][0]['value'] = $patient_state;
  if(!empty($patient_occupation)) $node->rd_f_patient_occupation['und'][0]['value'] = $patient_occupation;
  if(!empty($patient_recommended)) $node->rd_f_patient_recommended['und'][0]['value'] = $patient_recommended;
  if(!empty($patient_notes)) $node->rd_f_patient_notes['und'][0]['value'] = $patient_notes;
  if(!empty($patient_homeopathy)) $node->rd_f_patient_homeopathy['und'][0]['value'] = $patient_homeopathy;
  if(!empty($patient_c_medicine)) $node->rd_f_patient_c_medicine['und'][0]['value'] = $patient_c_medicine;
  if(!empty($patient_a_therapies)) $node->rd_f_patient_a_therapies['und'][0]['value'] = $patient_a_therapies;
  if(!empty($patient_a_type)) $node->rd_f_patient_appo_type['und'][0]['value'] = $patient_a_type;
  if(!empty($patient_t_before)) $node->rd_f_patient_tried_before['und'][0]['value'] = $patient_t_before;
  if(!empty($patient_o_symptoms)) $node->rd_f_patient_o_symptoms['und'][0]['value'] = $patient_o_symptoms;
  // include access key ALL
  $key_all_terms = taxonomy_get_term_by_name('0 - All', 'rd_voc_access_key');
  $key_all_terms = array_keys($key_all_terms);
  $key_all_terms = reset($key_all_terms);
  $access_key_list[$key_all_terms] = $key_all_terms;
  //Access Key
  foreach ($access_key_list as $a_key => $a_value) {
    if( $a_value != 0){
      if(isset($node->rd_f_access_key['und'][0])){
        //verify the key doesn't already exist
        $key_exists = false;
        foreach ($node->rd_f_access_key['und'] as $key_node => $value) {
          if($value['tid'] == $a_value) $key_exists = true;
        }
        if(!$key_exists) $node->rd_f_access_key['und'][]['tid'] = $a_value;
      }
      else {
        $node->rd_f_access_key['und'][0]['tid'] = $a_value;
      }
    }
  }
  //Centre
  foreach ($centre_list as $c_key => $c_value) {
    if( $c_value != 0){
      if(isset($node->rd_f_access_patient_centre['und'][0])){
        //verify the key doesn't already exist
        $key_exists = false;
        foreach ($node->rd_f_access_patient_centre['und'] as $key_node => $value) {
          if($value['tid'] == $c_value) $key_exists = true;
        }
        if(!$key_exists) $node->rd_f_access_patient_centre['und'][]['tid'] = $c_value;
      }
      else {
        $node->rd_f_access_patient_centre['und'][0]['tid'] = $c_value;
      }
    }
  }

  $node = node_submit($node); // Prepare node for saving
  node_save($node);
}


/**
 * This function runs when the batch processing is complete
 */
function rd_sec_import_finished() {
  drupal_set_message(t('Import Completed Successfully'));
}



/**
* Page callback for Create Patients Form
*/
function rd_sec_create_patients_form($form, &$form_state) {



  $form['submit_full_patient'] = array(
    '#markup' => l(
      t('Create full patient'),
      'node/add/rd-ct-patient',
      array(
        'attributes' => array(
          'class' => 'btn btn-success',
          'target'=>'_blank',
          ),
        //'query' => array('destination' => 'secretariat/patients/create')
        )
      ) . '<hr style="border-top: dotted 1px;" >',
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => true,
  );

  $form['first_surename'] = array(
    '#type' => 'textfield',
    '#title' => t('First Surname'),
    '#required' => true,
  );

  $form['second_surename'] = array(
    '#type' => 'textfield',
    '#title' => t('Second Surname'),
  );

  $form['excel_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Patient Number (Excel)'),
    '#required' => false,
  );
  // create default value array for access_keys
  // $access_keys = _get_vocabulary_terms('rd_voc_access_key');
  // foreach ($access_keys as $key => $value) {
  //   $default_values_access_keys[$key] = 0;
  // }
  // $key_all_terms = array_keys($access_keys);
  // $key_all_terms = reset($key_all_terms);
  // $default_values_access_keys[$key_all_terms] = $key_all_terms;
  $access_keys = _get_vocabulary_terms('rd_voc_access_key');
  unset($access_keys[current(array_keys($access_keys))]); //remove the first element of the list: "0 - All"
  $form['access_keys'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Access Key'),
    '#options' => $access_keys,
    //'#default_value' => $default_values_access_keys,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create'),
    '#submit' => array ('rd_sec_create_patients_form_submit'),
  );

  return $form;
}

function rd_sec_create_patients_form_validate($form, &$form_state) {
  if(!empty($form_state['values']['excel_number'])){
    if (!is_numeric($form_state['values']['excel_number'])){
      form_set_error('excel_number', t('Patient Number is not a number'));
    }
    else {
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'rd_ct_patient')
        ->fieldCondition('rd_f_patient_excel_number', 'value', $form_state['values']['excel_number'], '=')
        ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');
      $result = $query->execute();

      // update
      if (!empty($result['node'])) {
        form_set_error('excel_number', t('Patient Number already exists'));
      }
    }
  }
}

function rd_sec_create_patients_form_submit($form, &$form_state) {
  global $user;

  $node = new stdClass();
  $node->title = !empty($form_state['values']['second_surename']) ? strtoupper($form_state['values']['first_surename']) . ' ' . strtoupper($form_state['values']['second_surename']) . ', ' . ucfirst($form_state['values']['name']) : strtoupper($form_state['values']['first_surename'])  . ', ' . ucfirst($form_state['values']['name']);
  $node->type = 'rd_ct_patient';
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
  $node->uid = $user->uid;
  $node->rd_f_patient_name['und'][0]['value'] = ucfirst($form_state['values']['name']);
  $node->rd_f_patient_first_surname['und'][0]['value'] = strtoupper($form_state['values']['first_surename']);
  if(isset($form_state['values']['second_surename'])) $node->rd_f_patient_second_surname['und'][0]['value'] = strtoupper($form_state['values']['second_surename']);
  $node->rd_f_patient_excel_number['und'][0]['value'] = !empty($form_state['values']['excel_number'])? $form_state['values']['excel_number'] : 0 ;

  // include access key ALL
  $key_all_terms = _get_vocabulary_terms('rd_voc_access_key');;
  $key_all_terms = array_keys($key_all_terms);
  $key_all_terms = reset($key_all_terms);
  $form_state['values']['access_keys'][$key_all_terms] = $key_all_terms;
  foreach($form_state['values']['access_keys'] as $key => $tid){
    if($tid != 0) $node->rd_f_access_key['und'][] = array('tid' => $tid);
  }

  $node = node_submit($node); // Prepare node for saving
  node_save($node);
  //$form_state['redirect']  = 'SOME WHERE';

  drupal_set_message(t('Patient has been created : ' . $node->title));
}

// ACCESS KEYS


/**
* Page callback for Insert Access Key Form
*/
function rd_sec_create_access_key_form($form, &$form_state) {

  $form['access_keys'] = array(
    '#type' => 'textarea',
    '#title' => t('Access Keys'),
    '#description' => t('IMP: Enter one value per line'),
    '#required' => true,
    );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Insert'),
  );

  return $form;
}

function rd_sec_create_access_key_form_submit($form, &$form_state) {
  $access_keys = explode("\r", $form_state['values']['access_keys']);
  foreach ($access_keys as $key => $access_key) {
    _add_taxonomy_term($access_key, 'rd_voc_access_key');
  }
  drupal_set_message('Access Keys created');
}


/**
* Page callback for Link Access Key Form
*/
function rd_sec_link_access_key_form($form, &$form_state) {
  $access_keys = _get_vocabulary_terms('rd_voc_access_key');
  unset($access_keys[current(array_keys($access_keys))]); //remove the first element of the list: "0 - All"
  $form['access_key'] = array(
    '#type' => 'select',
    '#title' => t('Access Keys'),
    '#description' => t('Select the Access Key to link'),
    '#options' => $access_keys,
    '#required' => true,
    );
  $form['practitioners'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Practitioners'),
    '#description' => t('Select Practitioners whom you want to add the Access Key'),
    '#options' => _find_users_by_role('Practicioner'),
    );
  $form['patient_numbers'] = array(
    '#type' => 'textarea',
    '#title' => t('Patient Numbers'),
    '#description' => t('IMP: Enter one value per line. You can have blank values between lines'),
    '#required' => true,
    );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Insert'),
  );

  return $form;
}

function rd_sec_link_access_key_form_submit($form, &$form_state) {
  // Access Key taxonomy id
  $tid = $form_state['values']['access_key'];

  // Attach Access Key to Users
  foreach ($form_state['values']['practitioners'] as $uid => $value) {
    if( $value != 0){
      $user = user_load($uid);
      if(isset($user->rd_f_access_key['und'][0])){
        //verify the key is not already linked
        $key_exists = false;
        foreach ($user->rd_f_access_key['und'] as $key_user => $value) {
          if($value['tid'] == $tid) $key_exists = true;
        }
        if(!$key_exists) $user->rd_f_access_key['und'][]['tid'] = $tid;
      }
      else {
        $user->rd_f_access_key['und'][0]['tid'] = $tid;
      }
      user_save($user);
    }
  }

  // Attach Access Key to Patients
  $patient_numbers_list = explode("\r", $form_state['values']['patient_numbers']);
  $patient_numbers = array();
  foreach ($patient_numbers_list as $key => $patient_number) {
    if(is_numeric($patient_number)) $patient_numbers[] = $patient_number;
  }
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'rd_ct_patient')
    ->fieldCondition('rd_f_patient_excel_number', 'value', $patient_numbers, 'IN')
    ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');
  $result = $query->execute();

  if (!empty($result['node'])) {
    foreach (array_keys($result['node']) as $key_result => $nid) {
      $patient_node = node_load($nid);
      if(isset($patient_node->rd_f_access_key['und'][0])){
        //verify the key is not already linked
        $key_exists = false;
        foreach ($patient_node->rd_f_access_key['und'] as $key_node => $value) {
          if($value['tid'] == $tid) $key_exists = true;
        }
        if(!$key_exists) $patient_node->rd_f_access_key['und'][]['tid'] = $tid;
      }
      else {
        $patient_node->rd_f_access_key['und'][0]['tid'] = $tid;
      }
      node_save($patient_node);
    }
  }
  drupal_set_message('Access Key linked');
}



/**
* Page callback for Delete Access Key Form
*/
function rd_sec_delete_access_key_form($form, &$form_state) {
  $access_keys = _get_vocabulary_terms('rd_voc_access_key');
  unset($access_keys[current(array_keys($access_keys))]); //remove the first element of the list: "0 - All"
  $form['access_keys'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Access Keys'),
    '#description' => t('Select the Access Keys to delete'),
    '#options' => $access_keys,
    '#required' => true,
    );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Delete'),
  );

  return $form;
}

function rd_sec_delete_access_key_form_submit($form, &$form_state) {
  foreach($form_state['values']['access_keys'] as $array_key => $tid){

    // Remve Access Keys within Users
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'user')
      ->entityCondition('bundle', 'user')
      ->fieldCondition('rd_f_access_key', 'tid', $tid, '=')
      ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');
    $result = $query->execute();

    if (!empty($result['user'])) {
      foreach (array_keys($result['user']) as $key_result => $nid) {
        $user = user_load($nid);
        foreach ($user->rd_f_access_key['und'] as $key_user => $value) {
          if($value['tid'] == $tid) unset($user->rd_f_access_key['und'][$key_user]);
        }
        sort($user->rd_f_access_key['und']);
        user_save($user);
      }
    }

    // Remve Access Keys within Patients
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'rd_ct_patient')
      ->fieldCondition('rd_f_access_key', 'tid', $tid, '=')
      ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');
    $result = $query->execute();

    if (!empty($result['node'])) {
      foreach (array_keys($result['node']) as $key_result => $nid) {
        $node = node_load($nid);
        foreach ($node->rd_f_access_key['und'] as $key_node => $value) {
          if($value['tid'] == $tid) unset($node->rd_f_access_key['und'][$key_node]);
        }
        sort($node->rd_f_access_key['und']);
        node_save($node);
      }
    }

    // Remove Access Keys taxonomy terms
    taxonomy_term_delete($tid);
  }

  drupal_set_message(t('Access Keys deleted correctly'));
}


// *******************************************************************************************
//     VIEWS
// *******************************************************************************************


/**
* Implementation of hook_views_api().
*/
function rd_secretariat_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'rd_secretariat'),
  );
}



// *******************************************************************************************
//     NODE
// *******************************************************************************************

/**
 * Implements hook_node_submit().
 */
function rd_secretariat_node_submit($node, $form, &$form_state) {

  if ($node->type == 'rd_ct_patient'){
    // Excel number = 0 if field is empty
    if (!isset($node->rd_f_patient_excel_number['und'][0]['value'])){
      $node->rd_f_patient_excel_number['und'][0]['value'] = 0;
    }
  }
}
