<?php

// *******************************************************************************************
//     PERMISSIONS
// *******************************************************************************************

/**
 * Implements hook_permission().
 */
function vimn_twitter_voting_entities_permission() {
  return array(
    'moderate chat' => array(
      'title' => t('access secretariat actions'),
      'description' => t('Allow access to the secretariat actions'),
    ),
  );
}

// *******************************************************************************************
//     MENU
// *******************************************************************************************

/**
 * Implements hook_menu().
 */
function hook_menu() {
  $items['secretaria'] = array(
    'title' => t('Secretaria'),
    'page callback' => 'secretaria',
    'access arguments' => array('access secretariat actions'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  // $items['secretaria/insertar_clave_acceso'] = array(
  //   'title' => t('Insert Access Key'),
  //   'page callback' => 'example_feed',
  //   'access arguments' => array('access content'),
  //   'type' => MENU_CALLBACK,
  // );

  return $items;
}
