<?php

// *******************************************************************************************
//     PERMISSIONS
// *******************************************************************************************

/**
 * Implements hook_permission().
 */
function rd_patient_permission() {
  return array(
    t('view patient panel patient details region') => array(
      'title' => t('Patient Panel: View Patient Details region'),
      'description' => t('Allow to view Patient Details region within patient panel layout'),
    ),

    t('view patient panel forms region') => array(
      'title' => t('Patient Panel: View Forms region'),
      'description' => t('Allow to view Forms region within patient panel layout'),
    ),

    t('view patient panel actions region') => array(
      'title' => t('Patient Panel: View Actions region'),
      'description' => t('Allow to view Actions region within patient panel layout'),
    ),
  );
}

// *******************************************************************************************
//     VIEWS
// *******************************************************************************************

/**
* Implementation of hook_views_api().
*/
function rd_patient_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'rd_patient')
  );
}



// *******************************************************************************************
//     PANELS
// *******************************************************************************************

/**
* Implementation of hook_ctools_plugin_api().
*/
function rd_patient_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function rd_patient_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
    return "plugins/". $plugin;
  }
  if ($module == 'page_manager' && $plugin == 'content_types' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}
