<?php

$entityform_code = '
{
  "type" : "formulario_tabaco_test",
  "label" : "Test Tabaco",
  "data" : {
    "draftable" : 0,
    "draft_redirect_path" : "",
    "draft_button_text" : "",
    "draft_save_text" : { "value" : "", "format" : "treatment" },
    "submit_button_text" : "",
    "submit_confirm_msg" : "",
    "your_submissions" : "",
    "disallow_resubmit_msg" : "",
    "delete_confirm_msg" : "",
    "page_title_view" : "",
    "preview_page" : 0,
    "submission_page_title" : "\u003Cnone\u003E",
    "submission_text" : { "value" : "", "format" : "treatment" },
    "submission_show_submitted" : 1,
    "submissions_view" : "default",
    "user_submissions_view" : "default",
    "form_status" : "ENTITYFORM_OPEN",
    "roles" : { "3" : "3", "4" : "4", "5" : "5", "1" : 0, "2" : 0 },
    "resubmit_action" : "new",
    "redirect_path" : "",
    "instruction_pre" : { "value" : "", "format" : "treatment" }
  },
  "weight" : "0",
  "paths" : []
}
';
