<?php

//NOTE: Change the language code at the begigning of the function: XX_get_taxonomy_translations

function es_get_taxonomy_translations(){
  return array(
    'vocabularies' => array(
        'Group' => 'Grupo',
        'Digital Keyboard Button Type' => 'Tipo de Boton del Teclado Digital',
        ),
    'terms' => array(
        'Text' => 'Texto',
        'List' => 'Lista',
        'Core Button' => 'Boton del nucleo',
        'Germany' => 'Alemania',
        'France' => 'Francia',
        'Spain' => 'EspaNa',
        'Barcelona' => 'Barcelona',
        'Badalona' => 'Badalona',
        'Carme Centre' => 'Centro Carme',
        ),
    );
}
