<?php

//NOTE: Change the language code at the begigning of the function: XX_get_taxonomy_translations

function es_get_taxonomy_translations(){
  return array(
    'vocabularies' => array(
        'Access Key' => 'Clave de Acceso',
        'Centre' => 'Centro',
        'Products' => 'Productos',
        ),
    'terms' => array(
        '0 - All' => '0 - Todas',
        'Tobacco' => 'Tabaco',
        ),
    );
}
