<?php

// IMPORTANT !!
// NOTE: Change the language code at the begigning of the function: XX_get_taxonomy_translations

function fr_get_taxonomy_translations(){
  return array(
    'Text' => 'Texte',
    'List' => 'Liste',
    'Core Button' => 'Bouton de base',
    'Germany' => 'Allemagne',
    'France' => 'France',
    'Spain' => 'Espagne',
    'Barcelona' => 'Barcelona',
    'Badalona' => 'Badalona',
    'Carme Centre' => 'Centro Carme',
    );
}
