<?php

// *******************************************************************************************
//     ENTITYFORMS
// *******************************************************************************************

/**
 * Implements hook_default_entityform_type().
 */
function rd_forms_default_entityform_type() {
  $entityforms = array();

  $files = file_scan_directory(drupal_get_path('module', 'rd_forms') .'/entityforms', '/\.inc/');
  foreach ($files as $absolute => $file) {
    require $absolute;
    if (isset($entityform_code)) {
      $entityforms[$file->name] = entity_import(
        'entityform_type',
        $entityform_code
      );
    }
  }

  return $entityforms;
}



// *******************************************************************************************
//     VIEWS
// *******************************************************************************************


/**
* Implementation of hook_views_api().
*/
function rd_forms_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'rd_forms'),
  );
}



// *******************************************************************************************
//     PANELS
// *******************************************************************************************

/**
* Implementation of hook_ctools_plugin_api().
*/
function rd_forms_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function rd_forms_ctools_plugin_directory($module, $plugin) {
  // if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
  //   return "plugins/". $plugin;
  // }
  if ($module == 'page_manager' && $plugin == 'content_types' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

// *******************************************************************************************
//     RD_FORMS API
// *******************************************************************************************

/**
 * Implements hook_default_entityform_type().
 */
function _get_rdforms() {
  $entityform_info = entity_get_info('entityform');
  $rdforms = array();
  foreach($entityform_info['bundles'] as $form_key => $form_value){
    $rdforms[$form_key] = $form_value['label'];
  }

  return $rdforms;
}

