<?php

// *******************************************************************************************
//     ENTITYFORMS
// *******************************************************************************************

/**
 * Implements hook_default_entityform_type().
 */
function rd_forms_default_entityform_type() {
  $entityforms = array();

  $files = file_scan_directory(drupal_get_path('module', 'rd_forms') .'/entityforms', '/\.inc/');
  foreach ($files as $absolute => $file) {
    require $absolute;
    if (isset($entityform_code)) {
      $entityforms[$file->name] = entity_import(
        'entityform_type',
        $entityform_code
      );
    }
  }

  return $entityforms;
}



// *******************************************************************************************
//     VIEWS
// *******************************************************************************************


/**
* Implementation of hook_views_api().
*/
function rd_forms_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'rd_forms'),
  );
}

