<?php

// *******************************************************************************************
//     PANELS
// *******************************************************************************************

/**
* Implementation of hook_ctools_plugin_api().
*/
function rd_access_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_directory()
 */
function rd_access_ctools_plugin_directory($module, $plugin) {
  if ($module == "panels" && in_array($plugin, array('layouts', 'styles'))) {
    return "plugins/". $plugin;
  }
  if ($module == 'page_manager' && $plugin == 'content_types' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}



// *******************************************************************************************
//     PERMISSIONS
// *******************************************************************************************

/**
 * Implements hook_permission().
 */
function rd_access_permission() {
  return array(
    t('administer own user centre') => array(
      'title' => t('Administer own user centre'), 
      'description' => t('See User Centre field when editing your account details'),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function rd_access_form_alter(&$form, &$form_state, $form_id){
  if(isset($form_id) & $form_id == 'user_profile_form'){
    if (!user_access('administer own user centre')){
	  unset($form['rd_f_access_user_centre']);
	}
  }
}
